INPUT_SOURCE: data/input/
LIBRI_G_Lxx: libri_g_lxx/
LIBRI_Vulgata: libri_vulgata/
LIBRI_S_VL: S_VL_XML_osis/
LILA_TEXTLINKER: https://lila-erc.eu/LiLaTextLinker/processText
LILA_SPARQLEP: https://lila-erc.eu/sparql/lila_knowledge_base/sparql
NAMESPACES:
    its: http://itserr.it/data/
    efrbroo: http://erlangen-crm.org/efrbroo/
    orl: https://dantenetwork.it/ontology/orl/current/
    lemon: http://lemon-model.net/lemon#
    ecrm: https://erlangen-crm.org/current/
    olires: https://dantenetwork.it/ontology/olires/current/
    ontolex: http://www.w3.org/ns/lemon/ontolex#
    metont: https://dantenetwork.it/ontology/metont/current/
    cnt: http://www.w3.org/2011/content#
    syntit: https://dantenetwork.it/ontology/syntit/current/
    iront: https://dantenetwork.it/ontology/iront/current/
    tresont: https://itserr.it/ns/tresont/current/
    lila: http://lila-erc.eu/ontologies/lila/
    lilaLemma: http://lila-erc.eu/data/id/lemma/
    lilaIpoLemma: http://lila-erc.eu/data/id/hypolemma/
SIGLAOPERA: svl
TITOLOOPERA: Bibbia Sabatier
TEXTFILES:
    - Genesis
    - Exodus
    - Leviticus
    - Numbers
    - Deuteronomy
    - Joshua
    - Judges
    - Ruth
    - Samuel-1
    - Samuel-2
    - Kings-1
    - Kings-2
    - Chronicles-1
    - Chronicles-2
    - Esdrae-2
    - Tobit
    - Judith
    - Esther
    - Job
    - Proverbs
    - Ecclesiastes
    - Song-of-solomon
    - Wisdom
    - Sirach
    - Isaiah
    - Jeremiah
    - Lamentations
    - Baruch
    - Ezekiel
    - Daniel
    - Hosea
    - Joel
    - Amos
    - Obadiah
    - Jonah
    - Micah
    - Nahum
    - Habakkuk
    - Zephaniah
    - Haggai
    - Zechariah
    - Malachi
    - Maccabees-1
    - Maccabees-2
    - Matthew
    - Mark
    - Luke
    - John
    - Acts
    - Romans
    - Corinthians-1
    - Corinthians-2
    - Galatians
    - Ephesians
    - Philippians
    - Colossians
    - Thessalonians-1
    - Thessalonians-2
    - Timothy-1
    - Timothy-2
    - Titus
    - Philemon
    - Hebrews
    - James
    - Peter-1
    - Peter-2
    - John-1
    - John-2
    - John-3
    - Jude
    - Revelation
    - Esdrae-3


TITOLILIBRI: {
    'Gen':['Gen', 'Genesis', 'Genesis'],
    'Ex':['Exo', 'Exodus', 'Exodus'],
    'Lev':['Lev', 'Leviticus', 'Leviticus'],
    'Num':['Num', 'Numeri', 'Numbers'],
    'Deut':['Deu', 'Deuteronomium', 'Deuteronomy' ],
    'Josh':['Jos', 'Josue', 'Joshua'],
    'Judg':['Jdg', 'Iudicum', 'Judges'],
    'Ruth': ['Rut', 'Ruth', 'Ruth'],
    '1Sam':['1Sa', 'I Samuhel', 'I Regum', 'Samuel-1'],
    '2Sam':['2Sa', 'II Samuhel', 'II Regum', 'Samuel-2'],
    '1Kings':['1Ki', 'I Malachim', 'III Regum', 'Kings-1'],
    '2Kings':['2Ki', 'II Malachim', 'IV Regum', 'Kings-2'],
    '1Chr':['1Ch', 'I Verba Dierum', 'I Paralipomenon', 'Chronicles-1'],
    '2Chr':['2Ch', 'II Verba Dierum', 'II Paralipomenon', 'Chronicles-2'],
    'esdrae-2':['2Es', 'II Ezras', 'II Esdrae', 'Esdrae-2'],
    'Tob':['Tob', 'Tobias', 'Tobit'],
    'Judith':['Jud', 'Iudith', 'Judith'],
    'Esth':['Est', 'Hester', 'Esther'],
    'Job':['Job', 'Iob', 'Job'],
    # 'Psalms':['Pis', 'Psalmi iuxta Septuaginta'],
    # 'Psalms-iuxtra-hebraicum':['Pih', 'Psalmi iuxta Hebraicum'],
    'Prov':['Pro', 'Libri Salomonis', 'Proverbia', 'Proverbs'],
    'Eccl':['Ecc', 'Ecclesiastes', 'Ecclesiastes'],
    'Song':['Sos', 'Canticum Canticorum', 'Song-of-solomon'],
    'Wis':['Wis', 'Sapientia', 'Wisdom'],
    'Sir':['Sir', 'Sirach', 'Ecclesiasticus', 'Sirach'],
    'Is':['Isa', 'Isaias', 'Isaiah'],
    'Jeremiah':['Jer', 'Hieremias', 'Jeremiah'],
    'Ier':['Lam', 'Threni', 'Lamentationes', 'Lamentations'],
    'Bar':['Bar', 'Baruch', 'Baruch'],
    'Ezek':['Eze', 'Hiezechiel', 'Ezekiel'],
    'Dan':['Dan', 'Danihel', 'Daniel'],
    'Hos':['Hos', 'Osee', 'Hosea'],
    'Joel':['Joe', 'Iohel', 'Joel'],
    'Amos':['Amo', 'Amos', 'Amos'],
    'Obad':['Oba', 'Abdias', 'Obadiah'],
    'Jonah':['Jon', 'Ionas', 'Jonah'],
    'Mic':['Mic', 'Micha', 'Micah'],
    'Nah':['Nah', 'Naum', 'Nahum'],
    'Hab':['Hab', 'Abacuc', 'Habakkuk'],
    'Zeph':['Zep', 'Sofonias', 'Zephaniah'],
    'Hag':['Hag', 'Aggeus', 'Haggai'],
    'Zech':['Zac', 'Zaccharias', 'Zaccharias'],
    'Mal':['Mal', 'Malachi', 'Malachi'],
    '1Mac':['1Ma', 'I Macchabaeorum', 'Maccabees-1'],
    '2Mac':['2Ma', 'II Macchabaeorum', 'Maccabees-2'],
    'matthew':['Mat', 'Secundum Mattheum', 'Matthew'],
    'mark':['Mar', 'Secundum Marcum', 'Mark'],
    'luke':['Luk', 'Secundum Lucam', 'Luke'],
    'john':['Joh', 'Secundum Iohannem', 'John'],
    'acts':['Act', 'Actus Apostolorum', 'Acts'],
    'romans':['Rom', 'Ad Romanos', 'Romans'],
    'corinthians-1':['1Co', 'Ad Corinthios I', 'Corinthians-1'],
    'corinthians-2':['2Co', 'Ad Corinthios II', 'Corinthians-2'],
    'galatians':['Gal', 'Ad Galatas', 'Galatians'],
    'ephesians':['Eph', 'Ad Ephesios', 'Ephesians'],
    'philippians':['Phi', 'Ad Philippenses', 'Philippians'],
    'colossians':['Col', 'Ad Colossenses', 'Colossians'],
    'thessalonians-1':['1Th', 'Ad Thessalonicenses I', 'Thessalonians-1'],
    'thessalonians-2':['2Th', 'Ad Thessalonicenses II', 'Thessalonians-2'],
    'timothy-1':['1Ti', 'Ad Timotheum I', 'Timothy-1'],
    'timothy-2':['2Ti', 'Ad Timotheum II', 'Timothy-2'],
    'titus':['Tit', 'Ad Titum', 'Titus'],
    'philemon':['Phil', 'Ad Philemonem', 'Philemon'],
    'hebrews':['Heb', 'Ad Hebraeos', 'Hebrews'],
    'james':['Jam', 'Iacobi', 'James'],
    'peter-1':['1Pe', 'I Petri', 'Peter-1'],
    'peter-2':['2Pe', 'II Petri', 'Peter-2'],
    'john-1':['1Jh', 'I Iohannis', 'John-1'],
    'john-2':['2Jh', 'II Iohannis', 'John-2'],
    'john-3':['3Jh', 'III Iohannis', 'John-3'],
    'jude':['Jude', 'Iudae', 'Jude'],
    'revelation':['Rev', 'Apocalypsis', 'Revelation'],
    'Prayer-of-manasseh':['Pom', 'Oratio Manasse', 'Genesis'],
    'esdrae-3':['3Es', 'III Ezras', 'III Esdrae', 'Esdrae-3'],
    'Esdrae-4':['4Es', 'IVEzras', 'IV Esdrae', 'Esdrae-4'],
    'Psalm-151':['Psa', 'Psalmus CLI', 'Psalm-151'],
    'Laodicenses':['Lao', 'Ad Laodicenses', 'Genesis']
}

SIGLEPOS: {
    'SCONJ': ['subordinating_conjunction', 'a'],
    'NUM': ['numeral', 'b'],
    'PRON': ['pronoun', 'c'],
    'INTJ': ['interjection', 'd'],
    'DET': ['determiner', 'e'],
    'PROPN': ['proper_noun', 'f'],
    'ADP': ['adposition', 'g'],
    'CCONJ': ['coordinating_conjunction', 'h'],
    'ADV': ['adverb', 'i'],
    'ADJ': ['adjective', 'l'],
    'VERB': ['verb', 'm'],
    'AUX': ['verb', 'n'],
    'NOUN': ['noun', 'o'], 
    'PART': ['particle', 'p'],
    'PUNCT': ['punct', 'q']
}
